import { Routes } from '@angular/router';
import { LoginComponent } from './features/login/login.component';
import { DashboardComponent } from './features/dashboard/dashboard.component';
import { CustomerListComponent } from './features/customers/customer-list.component';
import { CustomerDetailComponent } from './features/customers/customer-detail.component';
import { DataImportComponent } from './features/data-import/data-import.component';
import { AnalyticsComponent } from './features/analytics/analytics.component';
import { OpportunitiesComponent } from './features/opportunities/opportunities.component';
import { BusinessCaseComponent } from './features/business-case/business-case.component';
import { WorkspaceComponent } from './features/workspace/workspace.component';
import { ReportsComponent } from './features/reports/reports.component';
import { ArchitectureMapComponent } from './features/architecture-map/architecture-map.component';
import { SourceSizingComponent } from './features/source-sizing/source-sizing.component';
import { LargestTablesComponent } from './features/largest-tables/largest-tables.component';
import { ModulesComponent } from './features/modules/modules.component';
import { DevelopmentComponent } from './features/development/development.component';
import { SolutionProposalComponent } from './features/solution-proposal/solution-proposal.component';

export const routes: Routes = [
  { path: '', redirectTo: 'reports', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: 'reports', component: ReportsComponent },
  { path: 'executive-summary', redirectTo: 'reports' },
  { path: 'yonetici-ozeti', redirectTo: 'reports' },
  { path: 'summary', redirectTo: 'reports' },
  { path: 'presentation', redirectTo: 'reports' },
  { path: 'modules', component: ModulesComponent },
  { path: 'moduller', redirectTo: 'modules', pathMatch: 'full' },
  { path: 'sap-uygulamalari', redirectTo: 'modules' },
  { path: 'development', component: DevelopmentComponent },
  { path: 'gelistirmeler', redirectTo: 'development' },
  { path: 'sap-customization', redirectTo: 'development' },
  { path: 'analytics', component: AnalyticsComponent },
  { path: 'sap-lisans-bulut', redirectTo: 'analytics' },
  { path: 'fue', redirectTo: 'analytics' },
  { path: 'source-sizing', component: SourceSizingComponent },
  { path: 'teknik-altyapi', redirectTo: 'source-sizing' },
  { path: 'source', redirectTo: 'source-sizing' },
  { path: 'dashboard', redirectTo: 'source-sizing' },
  { path: 'customer-summary', redirectTo: 'source-sizing' },
  { path: 'architecture-map', component: ArchitectureMapComponent },
  { path: 'largest-tables', component: LargestTablesComponent },
  { path: 'dvm', redirectTo: 'largest-tables' },
  { path: 'solution-proposal', component: SolutionProposalComponent },
  { path: 'cozum-onerisi', redirectTo: 'solution-proposal' },
  { path: 'yol-haritasi', redirectTo: 'solution-proposal' },
  { path: 'business-case', component: BusinessCaseComponent },
  { path: 'toplam-sahip-olma-maliyeti', redirectTo: 'business-case' },
  { path: 'tco', redirectTo: 'business-case' },
  { path: 'customers', component: CustomerListComponent },
  { path: 'customers/:id', component: CustomerDetailComponent },
  { path: 'data-import', component: DataImportComponent },
  { path: 'opportunities', component: OpportunitiesComponent },
  { path: 'workspace', redirectTo: 'reports' },
  { path: 'ai-assistant', redirectTo: 'reports' },
  { path: '**', redirectTo: 'login' }
];
